name: cat_breed_identifier
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.2
  get: 4.6.1
  image_picker: ^0.8.5
  tflite: ^1.1.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf
    - family: Brand Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf
